truora/minidyn

client_test.go, table.go
This pull request ensures that during a query in DynamoDB we add all items that have a match to the query and return a key for pagination only when we are not in the last page. Tests are adjusted to reflect this
Fix #4
=> Add support for using filters in minidyn queries and paginate

interpreter/language/ast.go, interpreter/language/evaluator.go, interpreter/language/evaluator_test.go, interpreter/language/lexer.go, interpreter/language/lexer_test.go, interpreter/language/parser.go, interpreter/language/parser_test.go, interpreter/language/token.go, interpreter/language_test.go
Why:
It is an important feature when working with maps
What:
- It adds the token DOT.
- It support parsing index expressions with dot.
- It implements the index expression with dot
evaluation.
Issue: #9
=> Implement index expressions for maps

interpreter/language/environment.go, interpreter/language/evaluator.go, interpreter/language/evaluator_test.go, interpreter/language/object.go
Why:
It was not working propertly with the
ExpressionAttributeNames had nested
field access.
What:
- It modifies the environment.Get method
support this notation.
Issue: #9
=> Fix ExpressionAttributeNames with nested notation

interpreter/language/evaluator.go, interpreter/language/evaluator_test.go
Why:
Reserved words are only for the top level
an not for the index identifiers.
What:
- It adds the boolean parameter toplevel to
identify when the reserved word should be
checked or not.
Issue: #11
=> Fix reserved words for map index fields

interpreter/language/evaluator_test.go, interpreter/language/object.go, interpreter/language/object_test.go
Why:
The update texts verification was not working
propertly becuase it was comparing dynamodb
values and they are not comprable values.
What:
- It converts the comparing objects to string
with the Inspect method to compare the
expected result with the actual result.
- It sorts the keys in the Map#Inspect result
to avoid random outputs.
Issue: #3
=> Fix update expression tests

client.go, interpreter/language.go, interpreter/language/ast.go, interpreter/language/ast_test.go, interpreter/language/evaluator.go, interpreter/language/evaluator_test.go, interpreter/language/mapper.go, interpreter/language/object.go, interpreter/language/parser.go, interpreter/language/parser_test.go, table.go
Implement Add action for update expression interpreter
Why:
It will help to complete the interpreter
implementation.
What:
- It changes the parsing of action in the
upddate expressions to make it easier to extend.
- It implements the ADD action logic.
- It changes the client to return the interpreter
error instead of panicing.
=> Implement update expression add action

interpreter/language/evaluator.go, interpreter/language/evaluator_test.go, interpreter/language/object.go, interpreter/language/object_test.go, interpreter/language/parser.go, interpreter/language/parser_test.go
Why:
It will help to complete the interpretation of
update expressions.
What:
- It defines the detachable object interface
- It implements the detachable interface for
StringSet NumberSet and BinarySet.
- It uses the new interface to implement the
evaluation of the DELETE action expression.
Issue: #3
=> Implement DELETE action for update expression

client.go, client_test.go
What:
- Adds validateSyntaxExpression function
- Uses regex to validate syntax
- Adds tests in client_test
Why:
- To ensure ExpressionAttributeNames are valid.
Issue: #2
=> Add syntax validation on ExpressionAttributeNames and ExpressionAttributeValues

client.go
What: Move the validation of expression attributes after,
client validates the forced error existence
Why: To return first the forced error
Issue: #44
=> Move validation after forced error return

client_test.go, interpreter/language/object.go
Why:
It will help to test possible errors in the update expression
interpreter implementation.
What:
- It adds basic tests for the update operations ADD, REMOVE,
and DELETE.
Issue: #3
=> Improve tests for update expression

client.go, client_test.go, index.go, key_schema.go, table.go, types.go
What:
It validates if the partition key has the type that
was declarated to create the index.
What:
- It improves the function goGetValue to identify if
the item field do not match the type provided.
- It return an error when getting the item's key
from the index schema fails
Issue: #41
=> Improve validation for index schema

interpreter/language/ast_test.go, interpreter/language/evaluator_test.go, interpreter/language/parser.go, interpreter/language/parser_test.go
Why:
It is very important to avoid making multiple
request to dynamodb to make diferent updates
actions.
What:
- It supports multiple type of actions in the
interpreter.
Issue: #56
=> Support multiple causes in Update Expressions

interpreter/language/evaluator.go, interpreter/language/evaluator_test.go
What:
- Add validation to ensure there are no reserved
words being used.
Why:
- It's important to detect reserved words as
they would give an error in dynamodb, you
should use ExpressionAttributeNames
Issue: #61
=> Validate left hand side identifiers in UpdateExpressions

aws-v1/client/client_test.go, aws-v1/client/mapper.go, aws-v1/client/minidyn.go
What: Return nil if attrs came nil or empty
Why: Do not create an empty map that has not
values
=> Return nil when attributes are nil

interpreter/language/evaluator.go, interpreter/language/evaluator_test.go
Why:
the update valid expression
`SET pokemons = list_append(if_not_exists(pokemons, :empty_list), :pkmns)`
It was failing because the interpreter
did not recognize the nested expresion as
an update expression.
What:
- It uses the EvalUpdate method to evaluate the nested expression in an update expression.
Issue #53
=> Fix nested if_not_exists function

aws-v2/client/client.go, aws-v2/client/client_test.go, aws-v2/client/mapper.go
Why:
The right error type is need to check
if an conditional expression failed or
if the resource is not found.
What:
- It maps the internal error to the sdk-v2 errors, for those cases.
Issue: #64
=> Fix error types for aws-sdk-v2

aws-v1/client/client_test.go, aws-v2/client/client_test.go, core/table.go, core/table_test.go
Why:
It is not working according with the documentation.
What:
- It fixes the conditions to return the last evaluated key when the limit was reached.
- It adds more test for query pagination
Issue: #73
=> Fix last evalauted key edge case on Query

aws-v2/client/client_test.go, aws-v2/client/mapper.go
Why:
It was incorretly lowering the keys names
breaking the conditional expression feature.
What:
- It removes the usage of strings.ToLower
Issue: #86
=> Fix aws-v2 object mapper

aws-v2/client/client.go, aws-v2/client/client_test.go
What: When dynamo not found the item is added to unprocessed list
Why: Have consistency with dynamo behavior
Issue: truora#88
=> Manage the not found exception as unprocessed key

aws-v2/client/client.go, aws-v2/client/client_test.go
What: Include forced failure in batch get item
Why: It is necessary to test the failure case
CAN-3647
=> Add the force failure support

aws-v2/client/client.go
What: Add forced failure support for batch write item
Why: To easily test failure cases
SPIC-4809
=> What: Add forced failure support for batch write item
